<a href="https://colab.research.google.com/github/202121405/bmt/blob/main/21505_10%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as  pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [11]:
type(s)

pandas.core.series.Series

In [13]:
dates = pd.date_range('20201113', periods=6)
dates

DatetimeIndex(['2020-11-13', '2020-11-14', '2020-11-15', '2020-11-16',
               '2020-11-17', '2020-11-18'],
              dtype='datetime64[ns]', freq='D')

In [17]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD')) 
df

A         B         C         D
2020-11-13 -1.159778  0.533576 -1.423254 -0.136933
2020-11-14  1.104592 -0.467886 -1.342332  1.221475
2020-11-15 -0.787108 -1.607984 -0.621429  1.443981
2020-11-16  0.820134  0.437943  1.363827  0.792386
2020-11-17  0.584495 -0.812996 -1.273546  0.329123
2020-11-18 -0.531233 -0.245963  0.484373 -0.620808

In [19]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=('A','B','C','D')) 
df

A         B         C         D
2020-11-13  0.311543 -0.256481  0.708617 -0.463063
2020-11-14 -1.703557 -0.346187  0.552435 -0.866188
2020-11-15 -0.533925  0.098488  0.087366 -0.435400
2020-11-16 -0.991257 -1.951541  0.019880  1.159219
2020-11-17 -1.155685  0.881180 -0.724877 -0.934983
2020-11-18 -0.481127  1.673436 -0.548039 -0.166635

In [26]:
df2 = pd.DataFrame(
    {
        'A': 1.,
        'B': pd.Timestamp('20201113'),
        'C': pd.Series(1, index=list(range(4)), dtype='float32'),
        'D': np.array([3] * 4, dtype='int32'),
        'E': pd.Categorical(["test", "train", "test", "train"]),
        'F': 'foo'
     }
)
df2

A          B    C  D      E    F
0  1.0 2020-11-13  1.0  3   test  foo
1  1.0 2020-11-13  1.0  3  train  foo
2  1.0 2020-11-13  1.0  3   test  foo
3  1.0 2020-11-13  1.0  3  train  foo

In [27]:
dates = pd.date_range('20201113', periods=6)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df.tail()

A         B         C         D
2020-11-14  1.492912  0.117595  1.243705  0.357719
2020-11-15  0.639743  1.633565 -2.885098 -0.279271
2020-11-16 -0.715294 -0.964493 -0.408410 -0.316843
2020-11-17 -1.237679  1.743324  1.364367 -0.165396
2020-11-18 -2.787265  1.912860  0.683716  0.496742

In [28]:
dates = pd.date_range('20201113', periods=6)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD')) 
df.head()

A         B         C         D
2020-11-13  3.025722  0.502345 -0.926418 -0.264513
2020-11-14  0.705140 -1.814447 -0.483945 -1.419307
2020-11-15  1.936954  0.730044 -1.484081  0.340886
2020-11-16 -2.121010  3.151588 -1.639236  0.545180
2020-11-17 -1.813663  0.036842  0.825437 -0.947362

In [29]:
dates = pd.date_range('20201113', periods=6)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD')) 
print(df.index) # 인덱스 보기
print(df.columns) # 열(항목) 보기
print()
print(df.values) # 값 보기
print()
print(df.describe()) # 데이터의 대략적인 통계적 정보 요약
print()
print(df)
print()
print(df.T) # 데이터를 전치
print()
print(df.sort_index(axis=1, ascending=True)) # 축 별로 정렬 : False(오름차순), True(내림차순)-default
print(df.sort_index(axis=1, ascending=False))
print()
print(df.sort_values(by='B')) # 값 별로 정렬
df.sort_values(by='B')

DatetimeIndex(['2020-11-13', '2020-11-14', '2020-11-15', '2020-11-16',
               '2020-11-17', '2020-11-18'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

[[ 1.97075507  0.92241994 -0.07373515  0.64553809]
 [ 2.02676544 -0.25735077  0.81334104 -0.47103859]
 [ 1.79805071 -0.46575331 -3.18051119  0.67566836]
 [-2.71340481 -1.41041808 -0.9096566   1.13272187]
 [ 2.43293983  0.76338213  0.56962148  2.33220346]
 [ 0.50858283  1.16266011  0.62957005 -1.28550594]]

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   1.003948  0.119157 -0.358562  0.504931
std    1.934817  0.997260  1.520494  1.260171
min   -2.713405 -1.410418 -3.180511 -1.285506
25%    0.830950 -0.413653 -0.700676 -0.191894
50%    1.884403  0.253016  0.247943  0.660603
75%    2.012763  0.882660  0.614583  1.018458
max    2.432940  1.162660  0.813341  2.332203

                   A         B         C         D
2020-11-13  1.9707

A         B         C         D
2020-11-16 -2.713405 -1.410418 -0.909657  1.132722
2020-11-15  1.798051 -0.465753 -3.180511  0.675668
2020-11-14  2.026765 -0.257351  0.813341 -0.471039
2020-11-17  2.432940  0.763382  0.569621  2.332203
2020-11-13  1.970755  0.922420 -0.073735  0.645538
2020-11-18  0.508583  1.162660  0.629570 -1.285506

In [30]:
dates = pd.date_range('20201113', periods=6)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD')) 

print(df);print()
print(df['A']);print() # df.A와 동일한 Series를 생성하는 단일 열을 선택
print(df[0:3]);print() # 행을 분할하는 []를 통해 선택
print(df['20201114':'20201116']) 

                   A         B         C         D
2020-11-13  1.061551 -0.113055  1.320218 -0.202748
2020-11-14  1.436311  0.258815  0.277523  1.083373
2020-11-15 -0.288776  1.180680  0.066432 -0.567334
2020-11-16  1.065021 -0.990755 -0.501533 -0.986891
2020-11-17  0.239762  0.018961  1.500827  0.811404
2020-11-18 -2.068121  0.027264 -0.301294 -0.354948

2020-11-13    1.061551
2020-11-14    1.436311
2020-11-15   -0.288776
2020-11-16    1.065021
2020-11-17    0.239762
2020-11-18   -2.068121
Freq: D, Name: A, dtype: float64

                   A         B         C         D
2020-11-13  1.061551 -0.113055  1.320218 -0.202748
2020-11-14  1.436311  0.258815  0.277523  1.083373
2020-11-15 -0.288776  1.180680  0.066432 -0.567334

                   A         B         C         D
2020-11-14  1.436311  0.258815  0.277523  1.083373
2020-11-15 -0.288776  1.180680  0.066432 -0.567334
2020-11-16  1.065021 -0.990755 -0.501533 -0.986891


In [31]:
df

A         B         C         D
2020-11-13  1.061551 -0.113055  1.320218 -0.202748
2020-11-14  1.436311  0.258815  0.277523  1.083373
2020-11-15 -0.288776  1.180680  0.066432 -0.567334
2020-11-16  1.065021 -0.990755 -0.501533 -0.986891
2020-11-17  0.239762  0.018961  1.500827  0.811404
2020-11-18 -2.068121  0.027264 -0.301294 -0.354948

In [32]:
df.loc['20201113':'20201115', ['A']]

A
2020-11-13  1.061551
2020-11-14  1.436311
2020-11-15 -0.288776

In [34]:
df[df.A > 0]

A         B         C         D
2020-11-13  1.061551 -0.113055  1.320218 -0.202748
2020-11-14  1.436311  0.258815  0.277523  1.083373
2020-11-16  1.065021 -0.990755 -0.501533 -0.986891
2020-11-17  0.239762  0.018961  1.500827  0.811404

In [35]:
df[df > 0]

A         B         C         D
2020-11-13  1.061551       NaN  1.320218       NaN
2020-11-14  1.436311  0.258815  0.277523  1.083373
2020-11-15       NaN  1.180680  0.066432       NaN
2020-11-16  1.065021       NaN       NaN       NaN
2020-11-17  0.239762  0.018961  1.500827  0.811404
2020-11-18       NaN  0.027264       NaN       NaN

In [36]:
df2 = df.copy()

In [38]:
df2 = df

In [41]:
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df

A         B         C         D      E
2020-11-13  1.061551 -0.113055  1.320218 -0.202748    one
2020-11-14  1.436311  0.258815  0.277523  1.083373    one
2020-11-15 -0.288776  1.180680  0.066432 -0.567334    two
2020-11-16  1.065021 -0.990755 -0.501533 -0.986891  three
2020-11-17  0.239762  0.018961  1.500827  0.811404   four
2020-11-18 -2.068121  0.027264 -0.301294 -0.354948  three

In [42]:
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2020-11-15 -0.288776  1.180680  0.066432 -0.567334   two
2020-11-17  0.239762  0.018961  1.500827  0.811404  four

In [45]:
dates = pd.date_range('20201113', periods=6)
df

A         B         C         D      E
2020-11-13  1.061551 -0.113055  1.320218 -0.202748    one
2020-11-14  1.436311  0.258815  0.277523  1.083373    one
2020-11-15 -0.288776  1.180680  0.066432 -0.567334    two
2020-11-16  1.065021 -0.990755 -0.501533 -0.986891  three
2020-11-17  0.239762  0.018961  1.500827  0.811404   four
2020-11-18 -2.068121  0.027264 -0.301294 -0.354948  three

In [46]:
df2 = df

In [52]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))


In [53]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20201113', periods=6))

In [54]:
df['F'] = s1

In [56]:
df.at[dates[0],'A'] = 0 
df.iat[0,1] = 0  
df.loc[:,'D'] = np.array([5] * len(df))

In [57]:
df2 = df
df2[df2>0] = -df2